issue #72 solved
JerryJeager/Will-Be-There pull request #77
Opened 2024-08-14 21:12 UTC by bosiljkatodic00

# Goal

All JavaScript files from dashboard have been migrated to TypeScript.

# Checklist

- [ ] This PR has been connected to the issue number #72

2024-08-15 03:32 UTC, JerryJeager requested changes
also resolve merge conflicts here, thanks

2024-08-15 03:43 UTC, JerryJeager requested changes

2024-08-15 03:43 UTC, JerryJeager commented on src/components/dashboard/EventForm.tsx
> +                <TextInput value={eventLink} readOnly={true} width="w-full" />
vercel deployment failed at the point, can you check it out: 
![Screenshot 2024-08-15 043826](https://github.com/user-attachments/assets/4aeb248a-7ab1-4833-8765-be5605d6bee8)

2024-08-15 10:02 UTC, bosiljkatodic00 commented on src/components/dashboard/EventForm.tsx
> +                <TextInput value={eventLink} readOnly={true} width="w-full" />
I have tried to resolve this, please check it out in last commit.

2024-08-15 19:00 UTC, JerryJeager requested changes

2024-08-16 06:49 UTC, bosiljkatodic00 commented on app/dashboard/events/[id]/guest-list/page.tsx
> +import { GuestListTable} from '../../../../../src/components/dashboard/GuestListTable';
This one needs to be imported this way.

2024-08-18 05:34 UTC, JerryJeager requested changes
Are you able to test the codes locally? There was a typescript issue from the guests page....
![Uploading Screenshot 2024-08-18 062431.jpg…]()

2024-08-18 05:37 UTC, JerryJeager commented
> Are you able to test the codes locally? There was a typescript issue from the dashboard page.... ![Screenshot 2024-08-18 062431](https://private-user-images.githubusercontent.com/103522273/358886318-de906b95-9dc7-4695-bd8d-2bb563a14d0e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTk2NTMsIm5iZiI6MTcyMzk1OTM1MywicGF0aCI6Ii8xMDM1MjIyNzMvMzU4ODg2MzE4LWRlOTA2Yjk1LTlkYzctNDY5NS1iZDhkLTJiYjU2M2ExNGQwZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwNTM1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2IwZGFlMGNhMmQwYzEzMjAzMDFiZjVhYTQ2MGIzODljODRjNWVhOGIwNTRmN2M3Y2UyNmMyY2ZmMGZjNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g1AlNhuWR5q111rQln5Bpv_QiQ_iqr8em31CFMaQ6Tc)

the accepted types for guest status are "pending" | "approved" | "rejected" | "accepted"

2024-08-21 15:57 UTC, JerryJeager approved these changes

2024-08-21 15:58 UTC, merged